# Generated by Django 4.2.4 on 2023-09-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stress_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
