# Generated by Django 4.2.4 on 2023-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_stressform_formsubmitbyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmitbyuser',
            name='stressform',
        ),
        migrations.AddField(
            model_name='formsubmitbyuser',
            name='stressform',
            field=models.ManyToManyField(to='user.stressform'),
        ),
    ]
