# Generated by Django 4.2.4 on 2023-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_formsubmitbyuser_stressform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmitbyuser',
            name='stressform',
        ),
        migrations.AddField(
            model_name='formsubmitbyuser',
            name='stressform',
            field=models.CharField(default='[]', max_length=300),
        ),
    ]
