# Generated by Django 4.2.4 on 2023-09-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_formsubmitbyuser_stressform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StressForm',
        ),
        migrations.RenameField(
            model_name='formsubmitbyuser',
            old_name='stressform',
            new_name='answer_array',
        ),
    ]
