# Generated by Django 4.2.4 on 2023-09-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_stressform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmitbyuser',
            name='answer_array',
            field=models.TextField(default='[]'),
        ),
    ]
