# Generated by Django 4.2.4 on 2023-09-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
