# Generated by Django 4.2.4 on 2023-09-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0004_alter_chatresponse_response'),
        ('peerchat', '0004_chatresponse_is_stressed'),
    ]

    operations = [
    ]
