# Generated by Django 4.2.4 on 2023-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0005_merge_20230914_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatresponse',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
