# Generated by Django 4.2.4 on 2023-09-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0008_stresseduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresseduser',
            name='form_csv',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='stresseduser',
            name='prompt_csv',
            field=models.URLField(),
        ),
    ]
