# Generated by Django 4.2.4 on 2023-09-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0009_alter_stresseduser_form_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresseduser',
            name='form_csv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
