# Generated by Django 4.2.4 on 2023-09-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0010_alter_stresseduser_form_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresseduser',
            name='prompt_csv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
