# Generated by Django 4.2.4 on 2023-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerchat', '0011_alter_stresseduser_prompt_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
